language: cpp
compiler:
  - gcc
# Change this to your needs
before_install:
  - sudo add-apt-repository -y ppa:zoogie/sdl2-snapshots
  - sudo add-apt-repository -y ppa:eugenesan/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq tinyxml2 tinyxml2-dev libsdl2 libsdl2-dev libsdl2-image libsdl2-image-dev libsdl2-ttf libsdl2-ttf-dev
script: cmake . && make